version: '3.8'
services:
    wsDB:
        image: mysql:8.0
        container_name: wsDB-mysql
        restart: always
        environment:
            MYSQL_DATABASE: 'wsDB'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'userpw'
            MYSQL_ROOT_PASSWORD: 'rootpw'
        ports:
            - '3306:3306'
        expose:
            - '3306'
        volumes:
            - mysql-db:/var/lib/mysql
            - ./ddl:/docker-entrypoint-initdb.d
    wsDB-sqlserver:
        image: mcr.microsoft.com/azure-sql-edge
        container_name: wsDB-sqlserver
        restart: always
        environment:
            ACCEPT_EULA: 'Y'
            SA_PASSWORD: 'wsDB#sa#pw'
        ports:
            - '1433:1433'
        expose:
            - '1433'
        volumes:
            - wsDB-db:/var/lib/mssql
            - ./ddl:/scripts
        command:
            - /bin/bash
            - -c
            - |
               /opt/mssql/bin/sqlservr &
               pid=$$!
               echo "Waiting for MS SQL to be available"
               /opt/mssql-tools/bin/sqlcmd -l 30 -S localhost -h-1 -V1 -U sa -P $$SA_PASSWORD -Q "SET NOCOUNT ON SELECT \"YAY WE ARE UP\" , @@servername"
               is_up=$$?
               while [ $$is_up -ne 0 ] ; do
                 echo -e $$(date)
                 /opt/mssql-tools/bin/sqlcmd -l 30 -S localhost -h-1 -V1 -U sa -P $$SA_PASSWORD -Q "SET NOCOUNT ON SELECT \"YAY WE ARE UP\" , @@servername"
                 is_up=$$?
                 sleep 5
               done
               for foo in /scripts/SQLServer*.ddl
                 do /opt/mssql-tools/bin/sqlcmd -U sa -P $$SA_PASSWORD -l 30 -e -i $$foo
               done
               trap "kill -15 $$pid" SIGTERM
               wait $$pid
               exit 0
volumes:
    wsDB-db:
    mysql-db:

